title: Mindol
description: Mindol's Blog
author: Mindol
avatar: /assets/img/profile.jpg
email: hhh57463@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: /assets/img/MinTa.png
social:
  name: Mindol
  links:
    - https://github.com/hhh57463
    - https://www.instagram.com/hhh57463
    # - https://sly-lemonade-717.notion.site/d6f467dc95934f8581ef33fe4e84ad17
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
